### ISSUE TITLE
Document requirement for libkrb5

### ISSUE THREAD

**Issue by jackric** [mdubourg001/glci#12]
I was experiencing this error when trying to install glci:
```
/bin/sh: 1: krb5-config: not found
gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack
```
The fix for me was to `apt install libkrb5-3` (on Ubuntu 20.04)

**Comment by mdubourg001** [comment]
Thank you for reporting this, could help other users encountering the issue. 👌 

Closing this as I can't really make anything to "fix" this.
