### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by MarcelHoell** [mdubourg001/glci#19]
If I run glci locally on Windows, I get the following error:
```
TypeError: Cannot read property 'indexOf' of undefined
✘  - default
```

**Comment by alexymik** [comment]
I had the same error and in my case this was due to not having an `image` set in `.gitlab-ci.yml`. I tried to use `gitlab/gitlab-runner` but that returned a separate error. My setup uses a `docker-compose.yml` that pulls in multiple images in various stages.

**Comment by weyert** [comment]
yeah, had the same, i fixed the issue where you had it defined as `image.name`

**Comment by mdubourg001** [comment]
There was an issue in the way I determined the image to use for a job.

Should be fixed in https://github.com/mdubourg001/glci/releases/tag/v0.1.1.

Thanks for reporting this !
