### ISSUE TITLE
Suggestion: Consider using Gitlab's parser

### ISSUE THREAD

**Issue by justfortherec** [mdubourg001/glci#28]
You might have considered this already. If so, please ignore and close this issue.

I really like the idea of `glci` and applaud you for starting it.

When trying out the tool, I noticed that not all of the keywords of the Gitlab reference are supported (yet). [btw: Thanks for addressing my issues immediately.] Now, I wonder how much sense it makes to keep trying to play catch up with the official reference. It is open source after all. Would it make sense and would it be possible to rely on Gitlab's official implementation of the parser and continue from there?

There are several potential blockers (too tight coupling with their runner implementation might be one). And maybe it would take out the fun for you. However, just speaking from the perspective of a potential user of this tool, I think this approach is at least worth to be considered. It might allow to quickly get a larger feature set working.

Again, this is just a suggestion and I am not mad if you ignore it :smiley:

**Comment by mdubourg001** [comment]
Hey there, that's an interesting proposal. I've thought about that as this would be perfect to be able to rely on the official implementation, but I've chosen not to do so for a simple reason: GitLab Runner is a huge GO project. It's not a real problem per se, as I could just learn GO, dig the source code, learn how it is architectured, fork it, and implement just what is needed, **but** as the language I master is JavaScript, I chosed to go with it.

My guess (maybe wrong), was that it would need more work to use the GitLab Runner complete implementation to create glci than just parsing the YAML file and "re-implementating" the keywords I needed. I still think this was a good choice as my goal is not to implement a 100% local working GitLab CI, but just a tool to help the set-up. Also, the small glci codebase is, IMO, simpler to contribute to.

This is really not a bad suggestion, maybe it could be a simpler way of doing, but I do not plan to go for it for the moment. Thanks for the idea tho ! 👌
