### ISSUE TITLE
gitlab-ci-local

### ISSUE THREAD

**Issue by firecow** [mdubourg001/glci#29]
Hey, I couldn't find any sane way to reach you @mdubourg001, so I hope its ok i'm doing it like this
I just wanted to let you know, that i've been working on https://github.com/firecow/gitlab-ci-local for a while and it has support for artifacts, rules, shell-executor, docker-executor and doesn't leave root owned files in project directories

**Comment by mdubourg001** [comment]
Hey there, so I gave a look to your project and it seems that we don't have the same goal here: my feeling is that `gitlab-ci-local` aims to completely reproduce the GitLab CI pipelines behavior locally with complete logging and full feature set. `glci` simply tries to avoid the common pitfalls of setting up multiple-jobs pipelines, of chosing which image to use, and of sharing the right artifacts between jobs, and not much more than that.

We have two different approach, each with its pros and cons ! But nice project of yours anyway :ok_hand:

I don't really know what was the end goal of this issue but I will close it for now, feel free to reopen it if needed.

**Comment by firecow** [comment]
It was just to let you know that the project existed, in case you wanted something from it. 
But yeah, you are probably right, our goals aren't the same.
Mine is to eliminate the need for build tools (make, grunt, gulp) and just utilize .gitlab-ci.yml workflow locally as well...
