### ISSUE TITLE
Child pipelines?

### ISSUE THREAD

**Issue by gilzow** [mdubourg001/glci#30]
I'm going to guess that this tool doesn't support [child pipelines](https://docs.gitlab.com/ee/ci/parent_child_pipelines.html)? When I try running a valid pipeline configuration that contains child pipelines, glci errors out with `TypeError: commands is not iterable` once it hits the job that triggers the child pipeline. Is this something you have on your roadmap?

**Comment by mdubourg001** [comment]
You guessed right, glci doesn't support child pipelines, and no, I'm not planning to implement the parent-child pipelines feature per-se, but I think this could be a good thing to allow the user pointing out a file to use in place of the `.gitlab-ci.yml` file, for example by allowing a `--yml=my_file.yml` CLI option. This would allow you to test your child pipelines locally. 

What do you think ? 

Also, thanks for reporting this :ok_hand:

**Comment by mdubourg001** [comment]
As discussed, I added the `--yml` option in the https://github.com/mdubourg001/glci/releases/tag/v0.4.0 release 👌
