### ISSUE TITLE
Docker in docker service support

### ISSUE THREAD

**Issue by julienripoche** [mdubourg001/glci#36]
Do you plan to add support for the `docker:dind` service ?
It currently seems to be ignored.
For this simple `.gitlab-ci.yml`:

```sh
stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run amazon/aws-cli
```
this the log that I get:
```
glci (v0.4.1)

   build   
-----------
|---------|
|  build  |
|---------|

-----------------------------------------------
Running job "build" for stage "build"
-----------------------------------------------

ℹ - Using existing image "docker:latest"
docker run amazon/aws-cli
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

✘  - build
```

**Comment by mdubourg001** [comment]
The support for this is not in the short-term roadmap no, but this could be nice to have. 

PRs are open so if this is important for you to get this feature quickly, and if you want to, you're welcome to implement it.

**Comment by julienripoche** [comment]
Thanks for your answer.

I have actually no experience in javascript.

But I'll keep looking for future versions ;)
