### ISSUE TITLE
Running git commands fail

### ISSUE THREAD

**Issue by frwickst** [mdubourg001/glci#4]
When running in GitLab CI the folder that you gets put in when running scripts is a Git repository. This means that for instance if you want to handle things like fetching submodules yourself, then you can do that. However, with `glci` it seems like that is not the case and the `.git` folder does not exist at all. This causes `git` commands such as `git submodule update --init --recursive` to fail.

The error, as expected is:
```
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by mdubourg001** [comment]
Thanks for reporting this, the `.git` directory was indeed not added to container project files. Should be fixed in https://github.com/mdubourg001/glci/releases/tag/v0.1.0.
